#端口号
server:
  port: 10086
#应用名称
spring:
  application:
    name: moyi-eureka
eureka:
  client:
    service-url:
      #注册中心访问地址
      defaultZone: http://127.0.0.1:${server.port}/eureka
    #是否将自己本身作为一个服务注册到注册中心中，默认为true
    register-with-eureka: false
    #是否拉取注册中心中的所有服务，默认为true
    fetch-registry: true
  #将当前注册中心服务强制为本机ip
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
